---
  name: Deploy to GitHub Pages
  
  on:
    pull_request:
      branches:
        - main
      paths:
        - "docs/**"
  
  jobs:
    build:
      name: Build Docusaurus
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Fetch and Build blog content
          uses: ./.github/actions/docusaurus
          with:
            token: ${{ secrets.GH_PAT }}
            branch: ${{ github.head_ref || github.ref_name }}
