---
  name: Deploy to GitHub Pages
  
  on:
    pull_request:
      branches:
        - main
      paths:
        - "docs/**"
  
  jobs:
    build:
      name: Build Docusaurus
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Fetch and Build blog content
          uses: ./.github/actions/docusaurus
          with:
            token: ${{ secrets.GH_PAT }}
            branch: ${{ github.head_ref || github.ref_name }}

    deploy:
      name: Deploy to GitHub Pages
      needs: build
  
      permissions:
        pages: write
        id-token: write
  
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
  
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
